borre: imagelib.c watershed.c desfoque.c black_white.c  borre.c ; \
  gcc imagelib.c black_white.c watershed.c desfoque.c  borre.c -lm -o borre;\

limpa : ; \
  rm -f borre\
  rm -f _imageBW.pgm\
  rm -f _mask1.pgm\
  rm -f saida.pgm\